// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CustomModel is the model entity for the CustomModel schema.
type CustomModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Virtual model name exposed to downstream.
	ModelID string `json:"model_id,omitempty"`
	// UpstreamGroupID holds the value of the "upstream_group_id" field.
	UpstreamGroupID int64 `json:"upstream_group_id,omitempty"`
	// Real upstream model name.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// System prompt to inject into requests.
	SystemPrompt string `json:"system_prompt,omitempty"`
	// Whether this custom model is active.
	Enabled bool `json:"enabled,omitempty"`
	// Description or notes about this custom model.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomModelQuery when eager-loading is set.
	Edges        CustomModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CustomModelEdges holds the relations/edges for other nodes in the graph.
type CustomModelEdges struct {
	// UpstreamGroup holds the value of the upstream_group edge.
	UpstreamGroup *Group `json:"upstream_group,omitempty"`
	// DownstreamGroups holds the value of the downstream_groups edge.
	DownstreamGroups []*Group `json:"downstream_groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UpstreamGroupOrErr returns the UpstreamGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomModelEdges) UpstreamGroupOrErr() (*Group, error) {
	if e.UpstreamGroup != nil {
		return e.UpstreamGroup, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "upstream_group"}
}

// DownstreamGroupsOrErr returns the DownstreamGroups value or an error if the edge
// was not loaded in eager-loading.
func (e CustomModelEdges) DownstreamGroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[1] {
		return e.DownstreamGroups, nil
	}
	return nil, &NotLoadedError{edge: "downstream_groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case custommodel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case custommodel.FieldID, custommodel.FieldUpstreamGroupID:
			values[i] = new(sql.NullInt64)
		case custommodel.FieldModelID, custommodel.FieldUpstreamModel, custommodel.FieldSystemPrompt, custommodel.FieldDescription:
			values[i] = new(sql.NullString)
		case custommodel.FieldCreatedAt, custommodel.FieldUpdatedAt, custommodel.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomModel fields.
func (_m *CustomModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case custommodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case custommodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case custommodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case custommodel.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case custommodel.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case custommodel.FieldUpstreamGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_group_id", values[i])
			} else if value.Valid {
				_m.UpstreamGroupID = value.Int64
			}
		case custommodel.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case custommodel.FieldSystemPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field system_prompt", values[i])
			} else if value.Valid {
				_m.SystemPrompt = value.String
			}
		case custommodel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case custommodel.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomModel.
// This includes values selected through modifiers, order, etc.
func (_m *CustomModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUpstreamGroup queries the "upstream_group" edge of the CustomModel entity.
func (_m *CustomModel) QueryUpstreamGroup() *GroupQuery {
	return NewCustomModelClient(_m.config).QueryUpstreamGroup(_m)
}

// QueryDownstreamGroups queries the "downstream_groups" edge of the CustomModel entity.
func (_m *CustomModel) QueryDownstreamGroups() *GroupQuery {
	return NewCustomModelClient(_m.config).QueryDownstreamGroups(_m)
}

// Update returns a builder for updating this CustomModel.
// Note that you need to call CustomModel.Unwrap() before calling this method if this CustomModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomModel) Update() *CustomModelUpdateOne {
	return NewCustomModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomModel) Unwrap() *CustomModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomModel) String() string {
	var builder strings.Builder
	builder.WriteString("CustomModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("upstream_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpstreamGroupID))
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("system_prompt=")
	builder.WriteString(_m.SystemPrompt)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteByte(')')
	return builder.String()
}

// CustomModels is a parsable slice of CustomModel.
type CustomModels []*CustomModel
