// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelUpdate is the builder for updating CustomModel entities.
type CustomModelUpdate struct {
	config
	hooks    []Hook
	mutation *CustomModelMutation
}

// Where appends a list predicates to the CustomModelUpdate builder.
func (_u *CustomModelUpdate) Where(ps ...predicate.CustomModel) *CustomModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelUpdate) SetUpdatedAt(v time.Time) *CustomModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomModelUpdate) SetDeletedAt(v time.Time) *CustomModelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableDeletedAt(v *time.Time) *CustomModelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomModelUpdate) ClearDeletedAt() *CustomModelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *CustomModelUpdate) SetModelID(v string) *CustomModelUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableModelID(v *string) *CustomModelUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (_u *CustomModelUpdate) SetUpstreamGroupID(v int64) *CustomModelUpdate {
	_u.mutation.SetUpstreamGroupID(v)
	return _u
}

// SetNillableUpstreamGroupID sets the "upstream_group_id" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableUpstreamGroupID(v *int64) *CustomModelUpdate {
	if v != nil {
		_u.SetUpstreamGroupID(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *CustomModelUpdate) SetUpstreamModel(v string) *CustomModelUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableUpstreamModel(v *string) *CustomModelUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *CustomModelUpdate) SetSystemPrompt(v string) *CustomModelUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableSystemPrompt(v *string) *CustomModelUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *CustomModelUpdate) ClearSystemPrompt() *CustomModelUpdate {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CustomModelUpdate) SetEnabled(v bool) *CustomModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableEnabled(v *bool) *CustomModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomModelUpdate) SetDescription(v string) *CustomModelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomModelUpdate) SetNillableDescription(v *string) *CustomModelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CustomModelUpdate) ClearDescription() *CustomModelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpstreamGroup sets the "upstream_group" edge to the Group entity.
func (_u *CustomModelUpdate) SetUpstreamGroup(v *Group) *CustomModelUpdate {
	return _u.SetUpstreamGroupID(v.ID)
}

// AddDownstreamGroupIDs adds the "downstream_groups" edge to the Group entity by IDs.
func (_u *CustomModelUpdate) AddDownstreamGroupIDs(ids ...int64) *CustomModelUpdate {
	_u.mutation.AddDownstreamGroupIDs(ids...)
	return _u
}

// AddDownstreamGroups adds the "downstream_groups" edges to the Group entity.
func (_u *CustomModelUpdate) AddDownstreamGroups(v ...*Group) *CustomModelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownstreamGroupIDs(ids...)
}

// Mutation returns the CustomModelMutation object of the builder.
func (_u *CustomModelUpdate) Mutation() *CustomModelMutation {
	return _u.mutation
}

// ClearUpstreamGroup clears the "upstream_group" edge to the Group entity.
func (_u *CustomModelUpdate) ClearUpstreamGroup() *CustomModelUpdate {
	_u.mutation.ClearUpstreamGroup()
	return _u
}

// ClearDownstreamGroups clears all "downstream_groups" edges to the Group entity.
func (_u *CustomModelUpdate) ClearDownstreamGroups() *CustomModelUpdate {
	_u.mutation.ClearDownstreamGroups()
	return _u
}

// RemoveDownstreamGroupIDs removes the "downstream_groups" edge to Group entities by IDs.
func (_u *CustomModelUpdate) RemoveDownstreamGroupIDs(ids ...int64) *CustomModelUpdate {
	_u.mutation.RemoveDownstreamGroupIDs(ids...)
	return _u
}

// RemoveDownstreamGroups removes "downstream_groups" edges to Group entities.
func (_u *CustomModelUpdate) RemoveDownstreamGroups(v ...*Group) *CustomModelUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownstreamGroupIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomModelUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if custommodel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized custommodel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := custommodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelUpdate) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := custommodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "CustomModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := custommodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "CustomModel.upstream_model": %w`, err)}
		}
	}
	if _u.mutation.UpstreamGroupCleared() && len(_u.mutation.UpstreamGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModel.upstream_group"`)
	}
	return nil
}

func (_u *CustomModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodel.Table, custommodel.Columns, sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(custommodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(custommodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(custommodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(custommodel.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(custommodel.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(custommodel.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(custommodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(custommodel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(custommodel.FieldDescription, field.TypeString)
	}
	if _u.mutation.UpstreamGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   custommodel.UpstreamGroupTable,
			Columns: []string{custommodel.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpstreamGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   custommodel.UpstreamGroupTable,
			Columns: []string{custommodel.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownstreamGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownstreamGroupsIDs(); len(nodes) > 0 && !_u.mutation.DownstreamGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownstreamGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomModelUpdateOne is the builder for updating a single CustomModel entity.
type CustomModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomModelUpdateOne) SetUpdatedAt(v time.Time) *CustomModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomModelUpdateOne) SetDeletedAt(v time.Time) *CustomModelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableDeletedAt(v *time.Time) *CustomModelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomModelUpdateOne) ClearDeletedAt() *CustomModelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *CustomModelUpdateOne) SetModelID(v string) *CustomModelUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableModelID(v *string) *CustomModelUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (_u *CustomModelUpdateOne) SetUpstreamGroupID(v int64) *CustomModelUpdateOne {
	_u.mutation.SetUpstreamGroupID(v)
	return _u
}

// SetNillableUpstreamGroupID sets the "upstream_group_id" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableUpstreamGroupID(v *int64) *CustomModelUpdateOne {
	if v != nil {
		_u.SetUpstreamGroupID(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *CustomModelUpdateOne) SetUpstreamModel(v string) *CustomModelUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableUpstreamModel(v *string) *CustomModelUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *CustomModelUpdateOne) SetSystemPrompt(v string) *CustomModelUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableSystemPrompt(v *string) *CustomModelUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (_u *CustomModelUpdateOne) ClearSystemPrompt() *CustomModelUpdateOne {
	_u.mutation.ClearSystemPrompt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *CustomModelUpdateOne) SetEnabled(v bool) *CustomModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableEnabled(v *bool) *CustomModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CustomModelUpdateOne) SetDescription(v string) *CustomModelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CustomModelUpdateOne) SetNillableDescription(v *string) *CustomModelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *CustomModelUpdateOne) ClearDescription() *CustomModelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUpstreamGroup sets the "upstream_group" edge to the Group entity.
func (_u *CustomModelUpdateOne) SetUpstreamGroup(v *Group) *CustomModelUpdateOne {
	return _u.SetUpstreamGroupID(v.ID)
}

// AddDownstreamGroupIDs adds the "downstream_groups" edge to the Group entity by IDs.
func (_u *CustomModelUpdateOne) AddDownstreamGroupIDs(ids ...int64) *CustomModelUpdateOne {
	_u.mutation.AddDownstreamGroupIDs(ids...)
	return _u
}

// AddDownstreamGroups adds the "downstream_groups" edges to the Group entity.
func (_u *CustomModelUpdateOne) AddDownstreamGroups(v ...*Group) *CustomModelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDownstreamGroupIDs(ids...)
}

// Mutation returns the CustomModelMutation object of the builder.
func (_u *CustomModelUpdateOne) Mutation() *CustomModelMutation {
	return _u.mutation
}

// ClearUpstreamGroup clears the "upstream_group" edge to the Group entity.
func (_u *CustomModelUpdateOne) ClearUpstreamGroup() *CustomModelUpdateOne {
	_u.mutation.ClearUpstreamGroup()
	return _u
}

// ClearDownstreamGroups clears all "downstream_groups" edges to the Group entity.
func (_u *CustomModelUpdateOne) ClearDownstreamGroups() *CustomModelUpdateOne {
	_u.mutation.ClearDownstreamGroups()
	return _u
}

// RemoveDownstreamGroupIDs removes the "downstream_groups" edge to Group entities by IDs.
func (_u *CustomModelUpdateOne) RemoveDownstreamGroupIDs(ids ...int64) *CustomModelUpdateOne {
	_u.mutation.RemoveDownstreamGroupIDs(ids...)
	return _u
}

// RemoveDownstreamGroups removes "downstream_groups" edges to Group entities.
func (_u *CustomModelUpdateOne) RemoveDownstreamGroups(v ...*Group) *CustomModelUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDownstreamGroupIDs(ids...)
}

// Where appends a list predicates to the CustomModelUpdate builder.
func (_u *CustomModelUpdateOne) Where(ps ...predicate.CustomModel) *CustomModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomModelUpdateOne) Select(field string, fields ...string) *CustomModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomModel entity.
func (_u *CustomModelUpdateOne) Save(ctx context.Context) (*CustomModel, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelUpdateOne) SaveX(ctx context.Context) *CustomModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomModelUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if custommodel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized custommodel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := custommodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelUpdateOne) check() error {
	if v, ok := _u.mutation.ModelID(); ok {
		if err := custommodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "CustomModel.model_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := custommodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "CustomModel.upstream_model": %w`, err)}
		}
	}
	if _u.mutation.UpstreamGroupCleared() && len(_u.mutation.UpstreamGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModel.upstream_group"`)
	}
	return nil
}

func (_u *CustomModelUpdateOne) sqlSave(ctx context.Context) (_node *CustomModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodel.Table, custommodel.Columns, sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, custommodel.FieldID)
		for _, f := range fields {
			if !custommodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != custommodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(custommodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(custommodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(custommodel.FieldModelID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(custommodel.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(custommodel.FieldSystemPrompt, field.TypeString, value)
	}
	if _u.mutation.SystemPromptCleared() {
		_spec.ClearField(custommodel.FieldSystemPrompt, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(custommodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(custommodel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(custommodel.FieldDescription, field.TypeString)
	}
	if _u.mutation.UpstreamGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   custommodel.UpstreamGroupTable,
			Columns: []string{custommodel.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpstreamGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   custommodel.UpstreamGroupTable,
			Columns: []string{custommodel.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DownstreamGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDownstreamGroupsIDs(); len(nodes) > 0 && !_u.mutation.DownstreamGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DownstreamGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
