// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CustomModelCreate is the builder for creating a CustomModel entity.
type CustomModelCreate struct {
	config
	mutation *CustomModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomModelCreate) SetCreatedAt(v time.Time) *CustomModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableCreatedAt(v *time.Time) *CustomModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomModelCreate) SetUpdatedAt(v time.Time) *CustomModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableUpdatedAt(v *time.Time) *CustomModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CustomModelCreate) SetDeletedAt(v time.Time) *CustomModelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableDeletedAt(v *time.Time) *CustomModelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetModelID sets the "model_id" field.
func (_c *CustomModelCreate) SetModelID(v string) *CustomModelCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (_c *CustomModelCreate) SetUpstreamGroupID(v int64) *CustomModelCreate {
	_c.mutation.SetUpstreamGroupID(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *CustomModelCreate) SetUpstreamModel(v string) *CustomModelCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *CustomModelCreate) SetSystemPrompt(v string) *CustomModelCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableSystemPrompt(v *string) *CustomModelCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetInjectionMode sets the "injection_mode" field.
func (_c *CustomModelCreate) SetInjectionMode(v string) *CustomModelCreate {
	_c.mutation.SetInjectionMode(v)
	return _c
}

// SetNillableInjectionMode sets the "injection_mode" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableInjectionMode(v *string) *CustomModelCreate {
	if v != nil {
		_c.SetInjectionMode(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *CustomModelCreate) SetEnabled(v bool) *CustomModelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableEnabled(v *bool) *CustomModelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *CustomModelCreate) SetDescription(v string) *CustomModelCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *CustomModelCreate) SetNillableDescription(v *string) *CustomModelCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUpstreamGroup sets the "upstream_group" edge to the Group entity.
func (_c *CustomModelCreate) SetUpstreamGroup(v *Group) *CustomModelCreate {
	return _c.SetUpstreamGroupID(v.ID)
}

// AddDownstreamGroupIDs adds the "downstream_groups" edge to the Group entity by IDs.
func (_c *CustomModelCreate) AddDownstreamGroupIDs(ids ...int64) *CustomModelCreate {
	_c.mutation.AddDownstreamGroupIDs(ids...)
	return _c
}

// AddDownstreamGroups adds the "downstream_groups" edges to the Group entity.
func (_c *CustomModelCreate) AddDownstreamGroups(v ...*Group) *CustomModelCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDownstreamGroupIDs(ids...)
}

// Mutation returns the CustomModelMutation object of the builder.
func (_c *CustomModelCreate) Mutation() *CustomModelMutation {
	return _c.mutation
}

// Save creates the CustomModel in the database.
func (_c *CustomModelCreate) Save(ctx context.Context) (*CustomModel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomModelCreate) SaveX(ctx context.Context) *CustomModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomModelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if custommodel.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized custommodel.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := custommodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if custommodel.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized custommodel.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := custommodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		v := custommodel.DefaultInjectionMode
		_c.mutation.SetInjectionMode(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := custommodel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomModelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomModel.updated_at"`)}
	}
	if _, ok := _c.mutation.ModelID(); !ok {
		return &ValidationError{Name: "model_id", err: errors.New(`ent: missing required field "CustomModel.model_id"`)}
	}
	if v, ok := _c.mutation.ModelID(); ok {
		if err := custommodel.ModelIDValidator(v); err != nil {
			return &ValidationError{Name: "model_id", err: fmt.Errorf(`ent: validator failed for field "CustomModel.model_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamGroupID(); !ok {
		return &ValidationError{Name: "upstream_group_id", err: errors.New(`ent: missing required field "CustomModel.upstream_group_id"`)}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "CustomModel.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := custommodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "CustomModel.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InjectionMode(); !ok {
		return &ValidationError{Name: "injection_mode", err: errors.New(`ent: missing required field "CustomModel.injection_mode"`)}
	}
	if v, ok := _c.mutation.InjectionMode(); ok {
		if err := custommodel.InjectionModeValidator(v); err != nil {
			return &ValidationError{Name: "injection_mode", err: fmt.Errorf(`ent: validator failed for field "CustomModel.injection_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "CustomModel.enabled"`)}
	}
	if len(_c.mutation.UpstreamGroupIDs()) == 0 {
		return &ValidationError{Name: "upstream_group", err: errors.New(`ent: missing required edge "CustomModel.upstream_group"`)}
	}
	return nil
}

func (_c *CustomModelCreate) sqlSave(ctx context.Context) (*CustomModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomModelCreate) createSpec() (*CustomModel, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(custommodel.Table, sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(custommodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(custommodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(custommodel.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.ModelID(); ok {
		_spec.SetField(custommodel.FieldModelID, field.TypeString, value)
		_node.ModelID = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(custommodel.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(custommodel.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.InjectionMode(); ok {
		_spec.SetField(custommodel.FieldInjectionMode, field.TypeString, value)
		_node.InjectionMode = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(custommodel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(custommodel.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if nodes := _c.mutation.UpstreamGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   custommodel.UpstreamGroupTable,
			Columns: []string{custommodel.UpstreamGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpstreamGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DownstreamGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   custommodel.DownstreamGroupsTable,
			Columns: custommodel.DownstreamGroupsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelCreate) OnConflict(opts ...sql.ConflictOption) *CustomModelUpsertOne {
	_c.conflict = opts
	return &CustomModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelCreate) OnConflictColumns(columns ...string) *CustomModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelUpsertOne{
		create: _c,
	}
}

type (
	// CustomModelUpsertOne is the builder for "upsert"-ing
	//  one CustomModel node.
	CustomModelUpsertOne struct {
		create *CustomModelCreate
	}

	// CustomModelUpsert is the "OnConflict" setter.
	CustomModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelUpsert) SetUpdatedAt(v time.Time) *CustomModelUpsert {
	u.Set(custommodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateUpdatedAt() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomModelUpsert) SetDeletedAt(v time.Time) *CustomModelUpsert {
	u.Set(custommodel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateDeletedAt() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomModelUpsert) ClearDeletedAt() *CustomModelUpsert {
	u.SetNull(custommodel.FieldDeletedAt)
	return u
}

// SetModelID sets the "model_id" field.
func (u *CustomModelUpsert) SetModelID(v string) *CustomModelUpsert {
	u.Set(custommodel.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateModelID() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldModelID)
	return u
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (u *CustomModelUpsert) SetUpstreamGroupID(v int64) *CustomModelUpsert {
	u.Set(custommodel.FieldUpstreamGroupID, v)
	return u
}

// UpdateUpstreamGroupID sets the "upstream_group_id" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateUpstreamGroupID() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldUpstreamGroupID)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *CustomModelUpsert) SetUpstreamModel(v string) *CustomModelUpsert {
	u.Set(custommodel.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateUpstreamModel() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldUpstreamModel)
	return u
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *CustomModelUpsert) SetSystemPrompt(v string) *CustomModelUpsert {
	u.Set(custommodel.FieldSystemPrompt, v)
	return u
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateSystemPrompt() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldSystemPrompt)
	return u
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *CustomModelUpsert) ClearSystemPrompt() *CustomModelUpsert {
	u.SetNull(custommodel.FieldSystemPrompt)
	return u
}

// SetInjectionMode sets the "injection_mode" field.
func (u *CustomModelUpsert) SetInjectionMode(v string) *CustomModelUpsert {
	u.Set(custommodel.FieldInjectionMode, v)
	return u
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateInjectionMode() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldInjectionMode)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *CustomModelUpsert) SetEnabled(v bool) *CustomModelUpsert {
	u.Set(custommodel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateEnabled() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldEnabled)
	return u
}

// SetDescription sets the "description" field.
func (u *CustomModelUpsert) SetDescription(v string) *CustomModelUpsert {
	u.Set(custommodel.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelUpsert) UpdateDescription() *CustomModelUpsert {
	u.SetExcluded(custommodel.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelUpsert) ClearDescription() *CustomModelUpsert {
	u.SetNull(custommodel.FieldDescription)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelUpsertOne) UpdateNewValues() *CustomModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(custommodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomModelUpsertOne) Ignore() *CustomModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelUpsertOne) DoNothing() *CustomModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelCreate.OnConflict
// documentation for more info.
func (u *CustomModelUpsertOne) Update(set func(*CustomModelUpsert)) *CustomModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelUpsertOne) SetUpdatedAt(v time.Time) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateUpdatedAt() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomModelUpsertOne) SetDeletedAt(v time.Time) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateDeletedAt() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomModelUpsertOne) ClearDeletedAt() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *CustomModelUpsertOne) SetModelID(v string) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateModelID() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateModelID()
	})
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (u *CustomModelUpsertOne) SetUpstreamGroupID(v int64) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpstreamGroupID(v)
	})
}

// UpdateUpstreamGroupID sets the "upstream_group_id" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateUpstreamGroupID() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpstreamGroupID()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *CustomModelUpsertOne) SetUpstreamModel(v string) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateUpstreamModel() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *CustomModelUpsertOne) SetSystemPrompt(v string) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateSystemPrompt() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *CustomModelUpsertOne) ClearSystemPrompt() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetInjectionMode sets the "injection_mode" field.
func (u *CustomModelUpsertOne) SetInjectionMode(v string) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetInjectionMode(v)
	})
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateInjectionMode() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateInjectionMode()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CustomModelUpsertOne) SetEnabled(v bool) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateEnabled() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *CustomModelUpsertOne) SetDescription(v string) *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelUpsertOne) UpdateDescription() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelUpsertOne) ClearDescription() *CustomModelUpsertOne {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *CustomModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomModelCreateBulk is the builder for creating many CustomModel entities in bulk.
type CustomModelCreateBulk struct {
	config
	err      error
	builders []*CustomModelCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomModel entities in the database.
func (_c *CustomModelCreateBulk) Save(ctx context.Context) ([]*CustomModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomModelCreateBulk) SaveX(ctx context.Context) []*CustomModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomModelUpsertBulk {
	_c.conflict = opts
	return &CustomModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelCreateBulk) OnConflictColumns(columns ...string) *CustomModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelUpsertBulk{
		create: _c,
	}
}

// CustomModelUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomModel nodes.
type CustomModelUpsertBulk struct {
	create *CustomModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelUpsertBulk) UpdateNewValues() *CustomModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(custommodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomModelUpsertBulk) Ignore() *CustomModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelUpsertBulk) DoNothing() *CustomModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelCreateBulk.OnConflict
// documentation for more info.
func (u *CustomModelUpsertBulk) Update(set func(*CustomModelUpsert)) *CustomModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomModelUpsertBulk) SetUpdatedAt(v time.Time) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateUpdatedAt() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomModelUpsertBulk) SetDeletedAt(v time.Time) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateDeletedAt() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomModelUpsertBulk) ClearDeletedAt() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetModelID sets the "model_id" field.
func (u *CustomModelUpsertBulk) SetModelID(v string) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateModelID() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateModelID()
	})
}

// SetUpstreamGroupID sets the "upstream_group_id" field.
func (u *CustomModelUpsertBulk) SetUpstreamGroupID(v int64) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpstreamGroupID(v)
	})
}

// UpdateUpstreamGroupID sets the "upstream_group_id" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateUpstreamGroupID() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpstreamGroupID()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *CustomModelUpsertBulk) SetUpstreamModel(v string) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateUpstreamModel() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *CustomModelUpsertBulk) SetSystemPrompt(v string) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateSystemPrompt() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateSystemPrompt()
	})
}

// ClearSystemPrompt clears the value of the "system_prompt" field.
func (u *CustomModelUpsertBulk) ClearSystemPrompt() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearSystemPrompt()
	})
}

// SetInjectionMode sets the "injection_mode" field.
func (u *CustomModelUpsertBulk) SetInjectionMode(v string) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetInjectionMode(v)
	})
}

// UpdateInjectionMode sets the "injection_mode" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateInjectionMode() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateInjectionMode()
	})
}

// SetEnabled sets the "enabled" field.
func (u *CustomModelUpsertBulk) SetEnabled(v bool) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateEnabled() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetDescription sets the "description" field.
func (u *CustomModelUpsertBulk) SetDescription(v string) *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *CustomModelUpsertBulk) UpdateDescription() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *CustomModelUpsertBulk) ClearDescription() *CustomModelUpsertBulk {
	return u.Update(func(s *CustomModelUpsert) {
		s.ClearDescription()
	})
}

// Exec executes the query.
func (u *CustomModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
