// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/custommodeldownstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelDownstreamGroupUpdate is the builder for updating CustomModelDownstreamGroup entities.
type CustomModelDownstreamGroupUpdate struct {
	config
	hooks    []Hook
	mutation *CustomModelDownstreamGroupMutation
}

// Where appends a list predicates to the CustomModelDownstreamGroupUpdate builder.
func (_u *CustomModelDownstreamGroupUpdate) Where(ps ...predicate.CustomModelDownstreamGroup) *CustomModelDownstreamGroupUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCustomModelID sets the "custom_model_id" field.
func (_u *CustomModelDownstreamGroupUpdate) SetCustomModelID(v int64) *CustomModelDownstreamGroupUpdate {
	_u.mutation.SetCustomModelID(v)
	return _u
}

// SetNillableCustomModelID sets the "custom_model_id" field if the given value is not nil.
func (_u *CustomModelDownstreamGroupUpdate) SetNillableCustomModelID(v *int64) *CustomModelDownstreamGroupUpdate {
	if v != nil {
		_u.SetCustomModelID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CustomModelDownstreamGroupUpdate) SetGroupID(v int64) *CustomModelDownstreamGroupUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CustomModelDownstreamGroupUpdate) SetNillableGroupID(v *int64) *CustomModelDownstreamGroupUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCustomModel sets the "custom_model" edge to the CustomModel entity.
func (_u *CustomModelDownstreamGroupUpdate) SetCustomModel(v *CustomModel) *CustomModelDownstreamGroupUpdate {
	return _u.SetCustomModelID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *CustomModelDownstreamGroupUpdate) SetGroup(v *Group) *CustomModelDownstreamGroupUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the CustomModelDownstreamGroupMutation object of the builder.
func (_u *CustomModelDownstreamGroupUpdate) Mutation() *CustomModelDownstreamGroupMutation {
	return _u.mutation
}

// ClearCustomModel clears the "custom_model" edge to the CustomModel entity.
func (_u *CustomModelDownstreamGroupUpdate) ClearCustomModel() *CustomModelDownstreamGroupUpdate {
	_u.mutation.ClearCustomModel()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *CustomModelDownstreamGroupUpdate) ClearGroup() *CustomModelDownstreamGroupUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomModelDownstreamGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelDownstreamGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomModelDownstreamGroupUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelDownstreamGroupUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelDownstreamGroupUpdate) check() error {
	if _u.mutation.CustomModelCleared() && len(_u.mutation.CustomModelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModelDownstreamGroup.custom_model"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModelDownstreamGroup.group"`)
	}
	return nil
}

func (_u *CustomModelDownstreamGroupUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodeldownstreamgroup.Table, custommodeldownstreamgroup.Columns, sqlgraph.NewFieldSpec(custommodeldownstreamgroup.FieldCustomModelID, field.TypeInt64), sqlgraph.NewFieldSpec(custommodeldownstreamgroup.FieldGroupID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CustomModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.CustomModelTable,
			Columns: []string{custommodeldownstreamgroup.CustomModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.CustomModelTable,
			Columns: []string{custommodeldownstreamgroup.CustomModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.GroupTable,
			Columns: []string{custommodeldownstreamgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.GroupTable,
			Columns: []string{custommodeldownstreamgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodeldownstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomModelDownstreamGroupUpdateOne is the builder for updating a single CustomModelDownstreamGroup entity.
type CustomModelDownstreamGroupUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomModelDownstreamGroupMutation
}

// SetCustomModelID sets the "custom_model_id" field.
func (_u *CustomModelDownstreamGroupUpdateOne) SetCustomModelID(v int64) *CustomModelDownstreamGroupUpdateOne {
	_u.mutation.SetCustomModelID(v)
	return _u
}

// SetNillableCustomModelID sets the "custom_model_id" field if the given value is not nil.
func (_u *CustomModelDownstreamGroupUpdateOne) SetNillableCustomModelID(v *int64) *CustomModelDownstreamGroupUpdateOne {
	if v != nil {
		_u.SetCustomModelID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *CustomModelDownstreamGroupUpdateOne) SetGroupID(v int64) *CustomModelDownstreamGroupUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *CustomModelDownstreamGroupUpdateOne) SetNillableGroupID(v *int64) *CustomModelDownstreamGroupUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetCustomModel sets the "custom_model" edge to the CustomModel entity.
func (_u *CustomModelDownstreamGroupUpdateOne) SetCustomModel(v *CustomModel) *CustomModelDownstreamGroupUpdateOne {
	return _u.SetCustomModelID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *CustomModelDownstreamGroupUpdateOne) SetGroup(v *Group) *CustomModelDownstreamGroupUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the CustomModelDownstreamGroupMutation object of the builder.
func (_u *CustomModelDownstreamGroupUpdateOne) Mutation() *CustomModelDownstreamGroupMutation {
	return _u.mutation
}

// ClearCustomModel clears the "custom_model" edge to the CustomModel entity.
func (_u *CustomModelDownstreamGroupUpdateOne) ClearCustomModel() *CustomModelDownstreamGroupUpdateOne {
	_u.mutation.ClearCustomModel()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *CustomModelDownstreamGroupUpdateOne) ClearGroup() *CustomModelDownstreamGroupUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the CustomModelDownstreamGroupUpdate builder.
func (_u *CustomModelDownstreamGroupUpdateOne) Where(ps ...predicate.CustomModelDownstreamGroup) *CustomModelDownstreamGroupUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomModelDownstreamGroupUpdateOne) Select(field string, fields ...string) *CustomModelDownstreamGroupUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomModelDownstreamGroup entity.
func (_u *CustomModelDownstreamGroupUpdateOne) Save(ctx context.Context) (*CustomModelDownstreamGroup, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomModelDownstreamGroupUpdateOne) SaveX(ctx context.Context) *CustomModelDownstreamGroup {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomModelDownstreamGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomModelDownstreamGroupUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomModelDownstreamGroupUpdateOne) check() error {
	if _u.mutation.CustomModelCleared() && len(_u.mutation.CustomModelIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModelDownstreamGroup.custom_model"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomModelDownstreamGroup.group"`)
	}
	return nil
}

func (_u *CustomModelDownstreamGroupUpdateOne) sqlSave(ctx context.Context) (_node *CustomModelDownstreamGroup, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(custommodeldownstreamgroup.Table, custommodeldownstreamgroup.Columns, sqlgraph.NewFieldSpec(custommodeldownstreamgroup.FieldCustomModelID, field.TypeInt64), sqlgraph.NewFieldSpec(custommodeldownstreamgroup.FieldGroupID, field.TypeInt64))
	if id, ok := _u.mutation.CustomModelID(); !ok {
		return nil, &ValidationError{Name: "custom_model_id", err: errors.New(`ent: missing "CustomModelDownstreamGroup.custom_model_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.GroupID(); !ok {
		return nil, &ValidationError{Name: "group_id", err: errors.New(`ent: missing "CustomModelDownstreamGroup.group_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !custommodeldownstreamgroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CustomModelCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.CustomModelTable,
			Columns: []string{custommodeldownstreamgroup.CustomModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.CustomModelTable,
			Columns: []string{custommodeldownstreamgroup.CustomModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.GroupTable,
			Columns: []string{custommodeldownstreamgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.GroupTable,
			Columns: []string{custommodeldownstreamgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomModelDownstreamGroup{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{custommodeldownstreamgroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
