// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/custommodeldownstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CustomModelDownstreamGroup is the model entity for the CustomModelDownstreamGroup schema.
type CustomModelDownstreamGroup struct {
	config `json:"-"`
	// CustomModelID holds the value of the "custom_model_id" field.
	CustomModelID int64 `json:"custom_model_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomModelDownstreamGroupQuery when eager-loading is set.
	Edges        CustomModelDownstreamGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CustomModelDownstreamGroupEdges holds the relations/edges for other nodes in the graph.
type CustomModelDownstreamGroupEdges struct {
	// CustomModel holds the value of the custom_model edge.
	CustomModel *CustomModel `json:"custom_model,omitempty"`
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CustomModelOrErr returns the CustomModel value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomModelDownstreamGroupEdges) CustomModelOrErr() (*CustomModel, error) {
	if e.CustomModel != nil {
		return e.CustomModel, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: custommodel.Label}
	}
	return nil, &NotLoadedError{edge: "custom_model"}
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomModelDownstreamGroupEdges) GroupOrErr() (*Group, error) {
	if e.Group != nil {
		return e.Group, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomModelDownstreamGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case custommodeldownstreamgroup.FieldCustomModelID, custommodeldownstreamgroup.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case custommodeldownstreamgroup.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomModelDownstreamGroup fields.
func (_m *CustomModelDownstreamGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case custommodeldownstreamgroup.FieldCustomModelID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field custom_model_id", values[i])
			} else if value.Valid {
				_m.CustomModelID = value.Int64
			}
		case custommodeldownstreamgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case custommodeldownstreamgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomModelDownstreamGroup.
// This includes values selected through modifiers, order, etc.
func (_m *CustomModelDownstreamGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCustomModel queries the "custom_model" edge of the CustomModelDownstreamGroup entity.
func (_m *CustomModelDownstreamGroup) QueryCustomModel() *CustomModelQuery {
	return NewCustomModelDownstreamGroupClient(_m.config).QueryCustomModel(_m)
}

// QueryGroup queries the "group" edge of the CustomModelDownstreamGroup entity.
func (_m *CustomModelDownstreamGroup) QueryGroup() *GroupQuery {
	return NewCustomModelDownstreamGroupClient(_m.config).QueryGroup(_m)
}

// Update returns a builder for updating this CustomModelDownstreamGroup.
// Note that you need to call CustomModelDownstreamGroup.Unwrap() before calling this method if this CustomModelDownstreamGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomModelDownstreamGroup) Update() *CustomModelDownstreamGroupUpdateOne {
	return NewCustomModelDownstreamGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomModelDownstreamGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomModelDownstreamGroup) Unwrap() *CustomModelDownstreamGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomModelDownstreamGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomModelDownstreamGroup) String() string {
	var builder strings.Builder
	builder.WriteString("CustomModelDownstreamGroup(")
	builder.WriteString("custom_model_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CustomModelID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CustomModelDownstreamGroups is a parsable slice of CustomModelDownstreamGroup.
type CustomModelDownstreamGroups []*CustomModelDownstreamGroup
