// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/custommodeldownstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// CustomModelDownstreamGroupCreate is the builder for creating a CustomModelDownstreamGroup entity.
type CustomModelDownstreamGroupCreate struct {
	config
	mutation *CustomModelDownstreamGroupMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCustomModelID sets the "custom_model_id" field.
func (_c *CustomModelDownstreamGroupCreate) SetCustomModelID(v int64) *CustomModelDownstreamGroupCreate {
	_c.mutation.SetCustomModelID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *CustomModelDownstreamGroupCreate) SetGroupID(v int64) *CustomModelDownstreamGroupCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomModelDownstreamGroupCreate) SetCreatedAt(v time.Time) *CustomModelDownstreamGroupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomModelDownstreamGroupCreate) SetNillableCreatedAt(v *time.Time) *CustomModelDownstreamGroupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCustomModel sets the "custom_model" edge to the CustomModel entity.
func (_c *CustomModelDownstreamGroupCreate) SetCustomModel(v *CustomModel) *CustomModelDownstreamGroupCreate {
	return _c.SetCustomModelID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *CustomModelDownstreamGroupCreate) SetGroup(v *Group) *CustomModelDownstreamGroupCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the CustomModelDownstreamGroupMutation object of the builder.
func (_c *CustomModelDownstreamGroupCreate) Mutation() *CustomModelDownstreamGroupMutation {
	return _c.mutation
}

// Save creates the CustomModelDownstreamGroup in the database.
func (_c *CustomModelDownstreamGroupCreate) Save(ctx context.Context) (*CustomModelDownstreamGroup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomModelDownstreamGroupCreate) SaveX(ctx context.Context) *CustomModelDownstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelDownstreamGroupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelDownstreamGroupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomModelDownstreamGroupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := custommodeldownstreamgroup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomModelDownstreamGroupCreate) check() error {
	if _, ok := _c.mutation.CustomModelID(); !ok {
		return &ValidationError{Name: "custom_model_id", err: errors.New(`ent: missing required field "CustomModelDownstreamGroup.custom_model_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "CustomModelDownstreamGroup.group_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomModelDownstreamGroup.created_at"`)}
	}
	if len(_c.mutation.CustomModelIDs()) == 0 {
		return &ValidationError{Name: "custom_model", err: errors.New(`ent: missing required edge "CustomModelDownstreamGroup.custom_model"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "CustomModelDownstreamGroup.group"`)}
	}
	return nil
}

func (_c *CustomModelDownstreamGroupCreate) sqlSave(ctx context.Context) (*CustomModelDownstreamGroup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *CustomModelDownstreamGroupCreate) createSpec() (*CustomModelDownstreamGroup, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomModelDownstreamGroup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(custommodeldownstreamgroup.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(custommodeldownstreamgroup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CustomModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.CustomModelTable,
			Columns: []string{custommodeldownstreamgroup.CustomModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(custommodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomModelID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   custommodeldownstreamgroup.GroupTable,
			Columns: []string{custommodeldownstreamgroup.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelDownstreamGroup.Create().
//		SetCustomModelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelDownstreamGroupUpsert) {
//			SetCustomModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelDownstreamGroupCreate) OnConflict(opts ...sql.ConflictOption) *CustomModelDownstreamGroupUpsertOne {
	_c.conflict = opts
	return &CustomModelDownstreamGroupUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelDownstreamGroupCreate) OnConflictColumns(columns ...string) *CustomModelDownstreamGroupUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelDownstreamGroupUpsertOne{
		create: _c,
	}
}

type (
	// CustomModelDownstreamGroupUpsertOne is the builder for "upsert"-ing
	//  one CustomModelDownstreamGroup node.
	CustomModelDownstreamGroupUpsertOne struct {
		create *CustomModelDownstreamGroupCreate
	}

	// CustomModelDownstreamGroupUpsert is the "OnConflict" setter.
	CustomModelDownstreamGroupUpsert struct {
		*sql.UpdateSet
	}
)

// SetCustomModelID sets the "custom_model_id" field.
func (u *CustomModelDownstreamGroupUpsert) SetCustomModelID(v int64) *CustomModelDownstreamGroupUpsert {
	u.Set(custommodeldownstreamgroup.FieldCustomModelID, v)
	return u
}

// UpdateCustomModelID sets the "custom_model_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsert) UpdateCustomModelID() *CustomModelDownstreamGroupUpsert {
	u.SetExcluded(custommodeldownstreamgroup.FieldCustomModelID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *CustomModelDownstreamGroupUpsert) SetGroupID(v int64) *CustomModelDownstreamGroupUpsert {
	u.Set(custommodeldownstreamgroup.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsert) UpdateGroupID() *CustomModelDownstreamGroupUpsert {
	u.SetExcluded(custommodeldownstreamgroup.FieldGroupID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelDownstreamGroupUpsertOne) UpdateNewValues() *CustomModelDownstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(custommodeldownstreamgroup.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomModelDownstreamGroupUpsertOne) Ignore() *CustomModelDownstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelDownstreamGroupUpsertOne) DoNothing() *CustomModelDownstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelDownstreamGroupCreate.OnConflict
// documentation for more info.
func (u *CustomModelDownstreamGroupUpsertOne) Update(set func(*CustomModelDownstreamGroupUpsert)) *CustomModelDownstreamGroupUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelDownstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCustomModelID sets the "custom_model_id" field.
func (u *CustomModelDownstreamGroupUpsertOne) SetCustomModelID(v int64) *CustomModelDownstreamGroupUpsertOne {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.SetCustomModelID(v)
	})
}

// UpdateCustomModelID sets the "custom_model_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsertOne) UpdateCustomModelID() *CustomModelDownstreamGroupUpsertOne {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.UpdateCustomModelID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CustomModelDownstreamGroupUpsertOne) SetGroupID(v int64) *CustomModelDownstreamGroupUpsertOne {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsertOne) UpdateGroupID() *CustomModelDownstreamGroupUpsertOne {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *CustomModelDownstreamGroupUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelDownstreamGroupCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelDownstreamGroupUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// CustomModelDownstreamGroupCreateBulk is the builder for creating many CustomModelDownstreamGroup entities in bulk.
type CustomModelDownstreamGroupCreateBulk struct {
	config
	err      error
	builders []*CustomModelDownstreamGroupCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomModelDownstreamGroup entities in the database.
func (_c *CustomModelDownstreamGroupCreateBulk) Save(ctx context.Context) ([]*CustomModelDownstreamGroup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomModelDownstreamGroup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomModelDownstreamGroupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomModelDownstreamGroupCreateBulk) SaveX(ctx context.Context) []*CustomModelDownstreamGroup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomModelDownstreamGroupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomModelDownstreamGroupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomModelDownstreamGroup.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomModelDownstreamGroupUpsert) {
//			SetCustomModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomModelDownstreamGroupCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomModelDownstreamGroupUpsertBulk {
	_c.conflict = opts
	return &CustomModelDownstreamGroupUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomModelDownstreamGroupCreateBulk) OnConflictColumns(columns ...string) *CustomModelDownstreamGroupUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomModelDownstreamGroupUpsertBulk{
		create: _c,
	}
}

// CustomModelDownstreamGroupUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomModelDownstreamGroup nodes.
type CustomModelDownstreamGroupUpsertBulk struct {
	create *CustomModelDownstreamGroupCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomModelDownstreamGroupUpsertBulk) UpdateNewValues() *CustomModelDownstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(custommodeldownstreamgroup.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomModelDownstreamGroup.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomModelDownstreamGroupUpsertBulk) Ignore() *CustomModelDownstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomModelDownstreamGroupUpsertBulk) DoNothing() *CustomModelDownstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomModelDownstreamGroupCreateBulk.OnConflict
// documentation for more info.
func (u *CustomModelDownstreamGroupUpsertBulk) Update(set func(*CustomModelDownstreamGroupUpsert)) *CustomModelDownstreamGroupUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomModelDownstreamGroupUpsert{UpdateSet: update})
	}))
	return u
}

// SetCustomModelID sets the "custom_model_id" field.
func (u *CustomModelDownstreamGroupUpsertBulk) SetCustomModelID(v int64) *CustomModelDownstreamGroupUpsertBulk {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.SetCustomModelID(v)
	})
}

// UpdateCustomModelID sets the "custom_model_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsertBulk) UpdateCustomModelID() *CustomModelDownstreamGroupUpsertBulk {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.UpdateCustomModelID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *CustomModelDownstreamGroupUpsertBulk) SetGroupID(v int64) *CustomModelDownstreamGroupUpsertBulk {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *CustomModelDownstreamGroupUpsertBulk) UpdateGroupID() *CustomModelDownstreamGroupUpsertBulk {
	return u.Update(func(s *CustomModelDownstreamGroupUpsert) {
		s.UpdateGroupID()
	})
}

// Exec executes the query.
func (u *CustomModelDownstreamGroupUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomModelDownstreamGroupCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomModelDownstreamGroupCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomModelDownstreamGroupUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
