// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/custommodel"
	"github.com/Wei-Shaw/sub2api/ent/custommodeldownstreamgroup"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelDownstreamGroupQuery is the builder for querying CustomModelDownstreamGroup entities.
type CustomModelDownstreamGroupQuery struct {
	config
	ctx             *QueryContext
	order           []custommodeldownstreamgroup.OrderOption
	inters          []Interceptor
	predicates      []predicate.CustomModelDownstreamGroup
	withCustomModel *CustomModelQuery
	withGroup       *GroupQuery
	modifiers       []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustomModelDownstreamGroupQuery builder.
func (_q *CustomModelDownstreamGroupQuery) Where(ps ...predicate.CustomModelDownstreamGroup) *CustomModelDownstreamGroupQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CustomModelDownstreamGroupQuery) Limit(limit int) *CustomModelDownstreamGroupQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CustomModelDownstreamGroupQuery) Offset(offset int) *CustomModelDownstreamGroupQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CustomModelDownstreamGroupQuery) Unique(unique bool) *CustomModelDownstreamGroupQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CustomModelDownstreamGroupQuery) Order(o ...custommodeldownstreamgroup.OrderOption) *CustomModelDownstreamGroupQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCustomModel chains the current query on the "custom_model" edge.
func (_q *CustomModelDownstreamGroupQuery) QueryCustomModel() *CustomModelQuery {
	query := (&CustomModelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(custommodeldownstreamgroup.Table, custommodeldownstreamgroup.CustomModelColumn, selector),
			sqlgraph.To(custommodel.Table, custommodel.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, custommodeldownstreamgroup.CustomModelTable, custommodeldownstreamgroup.CustomModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryGroup chains the current query on the "group" edge.
func (_q *CustomModelDownstreamGroupQuery) QueryGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(custommodeldownstreamgroup.Table, custommodeldownstreamgroup.GroupColumn, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, custommodeldownstreamgroup.GroupTable, custommodeldownstreamgroup.GroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CustomModelDownstreamGroup entity from the query.
// Returns a *NotFoundError when no CustomModelDownstreamGroup was found.
func (_q *CustomModelDownstreamGroupQuery) First(ctx context.Context) (*CustomModelDownstreamGroup, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{custommodeldownstreamgroup.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CustomModelDownstreamGroupQuery) FirstX(ctx context.Context) *CustomModelDownstreamGroup {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single CustomModelDownstreamGroup entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CustomModelDownstreamGroup entity is found.
// Returns a *NotFoundError when no CustomModelDownstreamGroup entities are found.
func (_q *CustomModelDownstreamGroupQuery) Only(ctx context.Context) (*CustomModelDownstreamGroup, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{custommodeldownstreamgroup.Label}
	default:
		return nil, &NotSingularError{custommodeldownstreamgroup.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CustomModelDownstreamGroupQuery) OnlyX(ctx context.Context) *CustomModelDownstreamGroup {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of CustomModelDownstreamGroups.
func (_q *CustomModelDownstreamGroupQuery) All(ctx context.Context) ([]*CustomModelDownstreamGroup, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CustomModelDownstreamGroup, *CustomModelDownstreamGroupQuery]()
	return withInterceptors[[]*CustomModelDownstreamGroup](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CustomModelDownstreamGroupQuery) AllX(ctx context.Context) []*CustomModelDownstreamGroup {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *CustomModelDownstreamGroupQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CustomModelDownstreamGroupQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CustomModelDownstreamGroupQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CustomModelDownstreamGroupQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CustomModelDownstreamGroupQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustomModelDownstreamGroupQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CustomModelDownstreamGroupQuery) Clone() *CustomModelDownstreamGroupQuery {
	if _q == nil {
		return nil
	}
	return &CustomModelDownstreamGroupQuery{
		config:          _q.config,
		ctx:             _q.ctx.Clone(),
		order:           append([]custommodeldownstreamgroup.OrderOption{}, _q.order...),
		inters:          append([]Interceptor{}, _q.inters...),
		predicates:      append([]predicate.CustomModelDownstreamGroup{}, _q.predicates...),
		withCustomModel: _q.withCustomModel.Clone(),
		withGroup:       _q.withGroup.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCustomModel tells the query-builder to eager-load the nodes that are connected to
// the "custom_model" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustomModelDownstreamGroupQuery) WithCustomModel(opts ...func(*CustomModelQuery)) *CustomModelDownstreamGroupQuery {
	query := (&CustomModelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomModel = query
	return _q
}

// WithGroup tells the query-builder to eager-load the nodes that are connected to
// the "group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustomModelDownstreamGroupQuery) WithGroup(opts ...func(*GroupQuery)) *CustomModelDownstreamGroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withGroup = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CustomModelID int64 `json:"custom_model_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CustomModelDownstreamGroup.Query().
//		GroupBy(custommodeldownstreamgroup.FieldCustomModelID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CustomModelDownstreamGroupQuery) GroupBy(field string, fields ...string) *CustomModelDownstreamGroupGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CustomModelDownstreamGroupGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = custommodeldownstreamgroup.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CustomModelID int64 `json:"custom_model_id,omitempty"`
//	}
//
//	client.CustomModelDownstreamGroup.Query().
//		Select(custommodeldownstreamgroup.FieldCustomModelID).
//		Scan(ctx, &v)
func (_q *CustomModelDownstreamGroupQuery) Select(fields ...string) *CustomModelDownstreamGroupSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CustomModelDownstreamGroupSelect{CustomModelDownstreamGroupQuery: _q}
	sbuild.label = custommodeldownstreamgroup.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CustomModelDownstreamGroupSelect configured with the given aggregations.
func (_q *CustomModelDownstreamGroupQuery) Aggregate(fns ...AggregateFunc) *CustomModelDownstreamGroupSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CustomModelDownstreamGroupQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !custommodeldownstreamgroup.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CustomModelDownstreamGroupQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CustomModelDownstreamGroup, error) {
	var (
		nodes       = []*CustomModelDownstreamGroup{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCustomModel != nil,
			_q.withGroup != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CustomModelDownstreamGroup).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CustomModelDownstreamGroup{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCustomModel; query != nil {
		if err := _q.loadCustomModel(ctx, query, nodes, nil,
			func(n *CustomModelDownstreamGroup, e *CustomModel) { n.Edges.CustomModel = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withGroup; query != nil {
		if err := _q.loadGroup(ctx, query, nodes, nil,
			func(n *CustomModelDownstreamGroup, e *Group) { n.Edges.Group = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CustomModelDownstreamGroupQuery) loadCustomModel(ctx context.Context, query *CustomModelQuery, nodes []*CustomModelDownstreamGroup, init func(*CustomModelDownstreamGroup), assign func(*CustomModelDownstreamGroup, *CustomModel)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CustomModelDownstreamGroup)
	for i := range nodes {
		fk := nodes[i].CustomModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(custommodel.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "custom_model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CustomModelDownstreamGroupQuery) loadGroup(ctx context.Context, query *GroupQuery, nodes []*CustomModelDownstreamGroup, init func(*CustomModelDownstreamGroup), assign func(*CustomModelDownstreamGroup, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CustomModelDownstreamGroup)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CustomModelDownstreamGroupQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CustomModelDownstreamGroupQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(custommodeldownstreamgroup.Table, custommodeldownstreamgroup.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withCustomModel != nil {
			_spec.Node.AddColumnOnce(custommodeldownstreamgroup.FieldCustomModelID)
		}
		if _q.withGroup != nil {
			_spec.Node.AddColumnOnce(custommodeldownstreamgroup.FieldGroupID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CustomModelDownstreamGroupQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(custommodeldownstreamgroup.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = custommodeldownstreamgroup.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CustomModelDownstreamGroupQuery) ForUpdate(opts ...sql.LockOption) *CustomModelDownstreamGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CustomModelDownstreamGroupQuery) ForShare(opts ...sql.LockOption) *CustomModelDownstreamGroupQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CustomModelDownstreamGroupGroupBy is the group-by builder for CustomModelDownstreamGroup entities.
type CustomModelDownstreamGroupGroupBy struct {
	selector
	build *CustomModelDownstreamGroupQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CustomModelDownstreamGroupGroupBy) Aggregate(fns ...AggregateFunc) *CustomModelDownstreamGroupGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CustomModelDownstreamGroupGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomModelDownstreamGroupQuery, *CustomModelDownstreamGroupGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CustomModelDownstreamGroupGroupBy) sqlScan(ctx context.Context, root *CustomModelDownstreamGroupQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CustomModelDownstreamGroupSelect is the builder for selecting fields of CustomModelDownstreamGroup entities.
type CustomModelDownstreamGroupSelect struct {
	*CustomModelDownstreamGroupQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CustomModelDownstreamGroupSelect) Aggregate(fns ...AggregateFunc) *CustomModelDownstreamGroupSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CustomModelDownstreamGroupSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomModelDownstreamGroupQuery, *CustomModelDownstreamGroupSelect](ctx, _s.CustomModelDownstreamGroupQuery, _s, _s.inters, v)
}

func (_s *CustomModelDownstreamGroupSelect) sqlScan(ctx context.Context, root *CustomModelDownstreamGroupQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
