// Code generated by ent, DO NOT EDIT.

package custommodel

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the custommodel type in the database.
	Label = "custom_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldUpstreamGroupID holds the string denoting the upstream_group_id field in the database.
	FieldUpstreamGroupID = "upstream_group_id"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldSystemPrompt holds the string denoting the system_prompt field in the database.
	FieldSystemPrompt = "system_prompt"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// EdgeUpstreamGroup holds the string denoting the upstream_group edge name in mutations.
	EdgeUpstreamGroup = "upstream_group"
	// EdgeDownstreamGroups holds the string denoting the downstream_groups edge name in mutations.
	EdgeDownstreamGroups = "downstream_groups"
	// Table holds the table name of the custommodel in the database.
	Table = "custom_models"
	// UpstreamGroupTable is the table that holds the upstream_group relation/edge.
	UpstreamGroupTable = "custom_models"
	// UpstreamGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	UpstreamGroupInverseTable = "groups"
	// UpstreamGroupColumn is the table column denoting the upstream_group relation/edge.
	UpstreamGroupColumn = "upstream_group_id"
	// DownstreamGroupsTable is the table that holds the downstream_groups relation/edge. The primary key declared below.
	DownstreamGroupsTable = "custom_model_downstream_groups"
	// DownstreamGroupsInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	DownstreamGroupsInverseTable = "groups"
)

// Columns holds all SQL columns for custommodel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldModelID,
	FieldUpstreamGroupID,
	FieldUpstreamModel,
	FieldSystemPrompt,
	FieldEnabled,
	FieldDescription,
}

var (
	// DownstreamGroupsPrimaryKey and DownstreamGroupsColumn2 are the table columns denoting the
	// primary key for the downstream_groups relation (M2M).
	DownstreamGroupsPrimaryKey = []string{"custom_model_id", "group_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ModelIDValidator is a validator for the "model_id" field. It is called by the builders before save.
	ModelIDValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the CustomModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByUpstreamGroupID orders the results by the upstream_group_id field.
func ByUpstreamGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamGroupID, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// BySystemPrompt orders the results by the system_prompt field.
func BySystemPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSystemPrompt, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByUpstreamGroupField orders the results by upstream_group field.
func ByUpstreamGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpstreamGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByDownstreamGroupsCount orders the results by downstream_groups count.
func ByDownstreamGroupsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDownstreamGroupsStep(), opts...)
	}
}

// ByDownstreamGroups orders the results by downstream_groups terms.
func ByDownstreamGroups(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDownstreamGroupsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUpstreamGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpstreamGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpstreamGroupTable, UpstreamGroupColumn),
	)
}
func newDownstreamGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DownstreamGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, DownstreamGroupsTable, DownstreamGroupsPrimaryKey...),
	)
}
