// Code generated by ent, DO NOT EDIT.

package custommodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldDeletedAt, v))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldModelID, v))
}

// UpstreamGroupID applies equality check predicate on the "upstream_group_id" field. It's identical to UpstreamGroupIDEQ.
func UpstreamGroupID(v int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpstreamGroupID, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpstreamModel, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldSystemPrompt, v))
}

// InjectionMode applies equality check predicate on the "injection_mode" field. It's identical to InjectionModeEQ.
func InjectionMode(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldInjectionMode, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldEnabled, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotNull(FieldDeletedAt))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContainsFold(FieldModelID, v))
}

// UpstreamGroupIDEQ applies the EQ predicate on the "upstream_group_id" field.
func UpstreamGroupIDEQ(v int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpstreamGroupID, v))
}

// UpstreamGroupIDNEQ applies the NEQ predicate on the "upstream_group_id" field.
func UpstreamGroupIDNEQ(v int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldUpstreamGroupID, v))
}

// UpstreamGroupIDIn applies the In predicate on the "upstream_group_id" field.
func UpstreamGroupIDIn(vs ...int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldUpstreamGroupID, vs...))
}

// UpstreamGroupIDNotIn applies the NotIn predicate on the "upstream_group_id" field.
func UpstreamGroupIDNotIn(vs ...int64) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldUpstreamGroupID, vs...))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptIsNil applies the IsNil predicate on the "system_prompt" field.
func SystemPromptIsNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIsNull(FieldSystemPrompt))
}

// SystemPromptNotNil applies the NotNil predicate on the "system_prompt" field.
func SystemPromptNotNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotNull(FieldSystemPrompt))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// InjectionModeEQ applies the EQ predicate on the "injection_mode" field.
func InjectionModeEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldInjectionMode, v))
}

// InjectionModeNEQ applies the NEQ predicate on the "injection_mode" field.
func InjectionModeNEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldInjectionMode, v))
}

// InjectionModeIn applies the In predicate on the "injection_mode" field.
func InjectionModeIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldInjectionMode, vs...))
}

// InjectionModeNotIn applies the NotIn predicate on the "injection_mode" field.
func InjectionModeNotIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldInjectionMode, vs...))
}

// InjectionModeGT applies the GT predicate on the "injection_mode" field.
func InjectionModeGT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldInjectionMode, v))
}

// InjectionModeGTE applies the GTE predicate on the "injection_mode" field.
func InjectionModeGTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldInjectionMode, v))
}

// InjectionModeLT applies the LT predicate on the "injection_mode" field.
func InjectionModeLT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldInjectionMode, v))
}

// InjectionModeLTE applies the LTE predicate on the "injection_mode" field.
func InjectionModeLTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldInjectionMode, v))
}

// InjectionModeContains applies the Contains predicate on the "injection_mode" field.
func InjectionModeContains(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContains(FieldInjectionMode, v))
}

// InjectionModeHasPrefix applies the HasPrefix predicate on the "injection_mode" field.
func InjectionModeHasPrefix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasPrefix(FieldInjectionMode, v))
}

// InjectionModeHasSuffix applies the HasSuffix predicate on the "injection_mode" field.
func InjectionModeHasSuffix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasSuffix(FieldInjectionMode, v))
}

// InjectionModeEqualFold applies the EqualFold predicate on the "injection_mode" field.
func InjectionModeEqualFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEqualFold(FieldInjectionMode, v))
}

// InjectionModeContainsFold applies the ContainsFold predicate on the "injection_mode" field.
func InjectionModeContainsFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContainsFold(FieldInjectionMode, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldEnabled, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.CustomModel {
	return predicate.CustomModel(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.CustomModel {
	return predicate.CustomModel(sql.FieldContainsFold(FieldDescription, v))
}

// HasUpstreamGroup applies the HasEdge predicate on the "upstream_group" edge.
func HasUpstreamGroup() predicate.CustomModel {
	return predicate.CustomModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UpstreamGroupTable, UpstreamGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUpstreamGroupWith applies the HasEdge predicate on the "upstream_group" edge with a given conditions (other predicates).
func HasUpstreamGroupWith(preds ...predicate.Group) predicate.CustomModel {
	return predicate.CustomModel(func(s *sql.Selector) {
		step := newUpstreamGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDownstreamGroups applies the HasEdge predicate on the "downstream_groups" edge.
func HasDownstreamGroups() predicate.CustomModel {
	return predicate.CustomModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, DownstreamGroupsTable, DownstreamGroupsPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDownstreamGroupsWith applies the HasEdge predicate on the "downstream_groups" edge with a given conditions (other predicates).
func HasDownstreamGroupsWith(preds ...predicate.Group) predicate.CustomModel {
	return predicate.CustomModel(func(s *sql.Selector) {
		step := newDownstreamGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomModel) predicate.CustomModel {
	return predicate.CustomModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomModel) predicate.CustomModel {
	return predicate.CustomModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomModel) predicate.CustomModel {
	return predicate.CustomModel(sql.NotPredicates(p))
}
