// Code generated by ent, DO NOT EDIT.

package custommodeldownstreamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the custommodeldownstreamgroup type in the database.
	Label = "custom_model_downstream_group"
	// FieldCustomModelID holds the string denoting the custom_model_id field in the database.
	FieldCustomModelID = "custom_model_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCustomModel holds the string denoting the custom_model edge name in mutations.
	EdgeCustomModel = "custom_model"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// CustomModelFieldID holds the string denoting the ID field of the CustomModel.
	CustomModelFieldID = "id"
	// GroupFieldID holds the string denoting the ID field of the Group.
	GroupFieldID = "id"
	// Table holds the table name of the custommodeldownstreamgroup in the database.
	Table = "custom_model_downstream_groups"
	// CustomModelTable is the table that holds the custom_model relation/edge.
	CustomModelTable = "custom_model_downstream_groups"
	// CustomModelInverseTable is the table name for the CustomModel entity.
	// It exists in this package in order to avoid circular dependency with the "custommodel" package.
	CustomModelInverseTable = "custom_models"
	// CustomModelColumn is the table column denoting the custom_model relation/edge.
	CustomModelColumn = "custom_model_id"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "custom_model_downstream_groups"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
)

// Columns holds all SQL columns for custommodeldownstreamgroup fields.
var Columns = []string{
	FieldCustomModelID,
	FieldGroupID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CustomModelDownstreamGroup queries.
type OrderOption func(*sql.Selector)

// ByCustomModelID orders the results by the custom_model_id field.
func ByCustomModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomModelID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCustomModelField orders the results by custom_model field.
func ByCustomModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomModelStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}
func newCustomModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, CustomModelColumn),
		sqlgraph.To(CustomModelInverseTable, CustomModelFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CustomModelTable, CustomModelColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, GroupColumn),
		sqlgraph.To(GroupInverseTable, GroupFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
	)
}
