// Code generated by ent, DO NOT EDIT.

package custommodeldownstreamgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomModelID applies equality check predicate on the "custom_model_id" field. It's identical to CustomModelIDEQ.
func CustomModelID(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldCustomModelID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldGroupID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CustomModelIDEQ applies the EQ predicate on the "custom_model_id" field.
func CustomModelIDEQ(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldCustomModelID, v))
}

// CustomModelIDNEQ applies the NEQ predicate on the "custom_model_id" field.
func CustomModelIDNEQ(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNEQ(FieldCustomModelID, v))
}

// CustomModelIDIn applies the In predicate on the "custom_model_id" field.
func CustomModelIDIn(vs ...int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldIn(FieldCustomModelID, vs...))
}

// CustomModelIDNotIn applies the NotIn predicate on the "custom_model_id" field.
func CustomModelIDNotIn(vs ...int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNotIn(FieldCustomModelID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCustomModel applies the HasEdge predicate on the "custom_model" edge.
func HasCustomModel() predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, CustomModelColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, CustomModelTable, CustomModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomModelWith applies the HasEdge predicate on the "custom_model" edge with a given conditions (other predicates).
func HasCustomModelWith(preds ...predicate.CustomModel) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(func(s *sql.Selector) {
		step := newCustomModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGroup applies the HasEdge predicate on the "group" edge.
func HasGroup() predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, GroupColumn),
			sqlgraph.Edge(sqlgraph.M2O, false, GroupTable, GroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGroupWith applies the HasEdge predicate on the "group" edge with a given conditions (other predicates).
func HasGroupWith(preds ...predicate.Group) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(func(s *sql.Selector) {
		step := newGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomModelDownstreamGroup) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomModelDownstreamGroup) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomModelDownstreamGroup) predicate.CustomModelDownstreamGroup {
	return predicate.CustomModelDownstreamGroup(sql.NotPredicates(p))
}
